#exceptions are raised when the program is syntactically correct,but the code results in error.
num1=int(input("enter number1:"))
num2=int(input("enter a number2:"))

result=num1/num2
print(result)
